/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.ur;

import org.junit.Test;

import com.cp.ur.UserRegistration;

import static org.junit.Assert.*;

public class UserRegistrationTest {

}
